# Getting to know WISPS

First, Let's add the wisps package to the `PATH`...

In [1]:
import sys, os
sys.path.append('../')

...and then import it.

In [3]:
import wisps
print "hello world"

hello world


Let's see what subpackages are contained in WISPS

In [5]:
import pkgutil
package = wisps
def get_submodules(package):
    for importer, modname, ispkg in pkgutil.iter_modules(package.__path__):
        print "Found submodule %s (is a package: %s)" % (modname, ispkg)
get_submodules(package)

Found submodule data_mgmt (is a package: True)
Found submodule grib2_to_nc (is a package: True)
Found submodule marine_to_nc (is a package: True)
Found submodule mathlib (is a package: True)
Found submodule metar_to_nc (is a package: True)
Found submodule mospred (is a package: True)
Found submodule nclib (is a package: True)
Found submodule registry (is a package: True)
Found submodule scripts (is a package: True)
Found submodule tdlpack_to_nc (is a package: True)
Found submodule test (is a package: True)


#### Taking a look at the data_mgmt subpackage

Modules in data_mgmt:

In [6]:
import wisps.data_mgmt
package = wisps.data_mgmt
get_submodules(package)

Found submodule Location (is a package: False)
Found submodule Process (is a package: False)
Found submodule Time (is a package: False)
Found submodule Wisps_data (is a package: False)
Found submodule fetch (is a package: False)
Found submodule nc_writable (is a package: False)
Found submodule reader (is a package: False)
Found submodule test (is a package: True)
Found submodule writer (is a package: False)


In [7]:
import wisps.data_mgmt.Wisps_data as wd

In [8]:
for i in dir(wd): print i

__abstractmethods__
__add__
__class__
__delattr__
__dict__
__doc__
__format__
__getattr__
__getattribute__
__hash__
__init__
__metaclass__
__module__
__new__
__reduce__
__reduce_ex__
__repr__
__setattr__
__sizeof__
__str__
__subclasshook__
__weakref__
_abc_cache
_abc_negative_cache
_abc_negative_cache_version
_abc_registry
_write_coordinate
_write_elev
_write_elev_bounds
_write_plev
_write_plev_bounds
_write_time_bounds
add_bounds_process
add_data
add_db_metadata
add_elev_attributes
add_fcstTime
add_leadTime
add_metadata
add_nc_data
add_nc_metadata
add_plev_attributes
add_process
add_source
add_to_database
change_data_type
check_correct_shape
check_dimensions
create_dimension
create_dimensions
get_cell_methods
get_chunk_size
get_coord_name
get_coordinate
get_data_type
get_dimensions
get_fill_value
get_forecast_reference_time
get_lead_time
get_observedProperty
get_phenom_time
get_process_str
get_result_time
get_source
get_time
get_time_bounds
get_variable_name
has_bounds
has_elev
has_el

In [10]:
print wd.__doc__


    WISPS data object for storing metadata and accompanied objects describing the variable.

    This class will attempt to
    gather information from the metadata database on a given property, but
    any gaps will need to be provided by the user. 

    Attributes:
        name (str): `quick fill` name that can be used to initialize variable from template.
        data (:obj:`np.array`): n-dimensional numpy array holding variable data.
        dimensions (:obj:`list` of str): The names of the dimensions--ordered by dimension.
        processes (:obj:`list` of :obj:`Process`): Process that modify this variable.
        metadata (dict): Metadata with key-value pairs.
        time (:obj:`list` of :obj:`Time`): Time objects describing this variable
        properties (dict): Metadata that will not be written to NetCDF file 
            that may be used internally.

    Args:
        name (str): `quick-fill` name that can be used to initialize variable from template.
        autofill (bo

Now, Let's create a variable  
A list of templates are available here: ../wisps/registery/netcdf.yml

In [11]:
myvar = wd('wind_speed')

In [13]:
print myvar


***** wind_speed ******
*
* dtype               : float64
* processes           : ( )
* dimensions          : []
* level               : 2
Metadata:
* comment             : Wind speed is set to -9 if winds are variable.
* name                : wind_speed
* valid_min           : 0.0
* coordinates         : elev
* long_name           : wind speed
* standard_name       : wind_speed
* units               : knot
* valid_max           : 75.0
* OM_observedProperty : https://codes.nws.noaa.gov/StatPP/Data/Met/Moment/WSpd

Shape: 
(0,)
Data: 
[]
[]



Create some dummy data

In [14]:
import numpy as np
my_wspd_data = np.random.rand(5,5) * 30
print my_wspd_data

[[ 28.87374018  10.25290673   6.64353024  12.74505772  21.07716114]
 [  5.83188437  13.56191844  18.56231085  21.0264135   20.90269642]
 [ 22.9068645   23.34291171  16.14120269  13.11267333  24.74473073]
 [ 28.75240412  29.23882016  10.70150573   4.07784075   7.29401451]
 [ 18.02419876  29.92394777  19.81769215   6.60959817  20.05961374]]


In [15]:
myvar.data = my_wspd_data

In [16]:
import wisps.data_mgmt.writer as writer

In [17]:
writer.write(myvar, 'test.nc')

ERROR:root:Problem: shape of data and number of dimensions dont match
ERROR:root:Problem: with, wind_speed
ERROR:root:dimensions of data not equal to dimensions attribute
ERROR:root:len of shape is: 3
ERROR:root:len of dims  is: 1
ERROR:root:Will not write wind_speed


ValueError: 

## Whoops!
We forgot to define the dimensions.

In [23]:
myvar.dimensions = ['x','y']
myvar.data = my_wspd_data

In [ ]:
writer.write(myvar, 'test.nc')


In [25]:
!ncdump -h test.nc


In [26]:
!rm test.nc

In [1]:
!echo "Done"

Done
